In [2]:
import numpy as np

In [4]:
a=np.array(5)
print(a)

5


In [6]:
np.ndim(a)

0

In [7]:
one=np.array([1,2,3,4,5])
two=np.array([[1,2,3],[4,5,6]])
three=np.array([[[1,2,3],[4,5,6],[7,9,8]]])
print(one)
print(two)
print(three)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 9 8]]]


In [9]:
print(np.ndim(one))
print(np.ndim(two))
print(np.ndim(three))

1
2
3


In [11]:
List1=[1,2,3.4,[5,6]]
arr=np.array([1,2,3,4,5])

In [13]:
arr=np.array([1,2,3.4,"apple"]) #converting all into strings

In [14]:
arr

array(['1', '2', '3.4', 'apple'], dtype='<U32')

In [16]:
arr=np.array([1,2,3,4,5])# allows mathematical operations
arr/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

->Array Consumes less memory compared to list
->Array are faster than lists

Array Indexing

In [18]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)

In [19]:
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
newarr=arr.reshape(2,3,2)
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

Array Indexing
        -> Array indexing is the same as accessing an array element
        -> access the array element by referring to its index number
           

In [22]:
arr=np.array([1,2,3,4])
print(arr[1])

2


In [23]:
print(arr[2]+ arr[3])#addition

7


In [26]:
two=np.array([[1,2,3],[4,5,6]])
print(two[0,1])
print(two[1,2])

2
6


In [39]:
three=np.array([[[1,2,3],[4,5,6]],[[7,9,8],[3,4,5]]])
print(three[0,1,2])
print(three[1,1,1])
print(three[1,0,1])
print(three)

6
4
9
[[[1 2 3]
  [4 5 6]]

 [[7 9 8]
  [3 4 5]]]
