In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],
          [4,5,6]])

In [3]:
np.append(a,[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.append(a,[[7,8,9]],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.append(a,[[5],[8]],axis=1) #axis not equal to 0 when we give like this

array([[1, 2, 3, 5],
       [4, 5, 6, 8]])

In [15]:
np.array([[1,2],[3,4],[5,6]])


array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
np.insert(a,3,[11,12]) # 3 is an index position

array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [17]:
np.insert(a,0,[11],axis=0)

array([[11, 11, 11],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [18]:
np.insert(a,0,[11,12,13],axis=0)

array([[11, 12, 13],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [20]:
np.delete(a,1)

array([1, 3, 4, 5, 6])

In [21]:
np.delete(a,1,axis=1)

array([[1, 3],
       [4, 6]])

In [25]:
np.ndim(a)

2

Hstack vs Vstack

Hstack-> is used to join two arrays Horizontally
Vstack-> is used to join two arrays Vertically


In [26]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a,b)

[1 2 3] [4 5 6]


In [29]:
result=np.hstack((a,b))
result

array([1, 2, 3, 4, 5, 6])

In [30]:
result=np.vstack((a,b))
print(result)

[[1 2 3]
 [4 5 6]]


Numpy Concatenation

-> It is used for joining two or more arrays of the same shape along a specified axis
-> Axis=0, Adding new rows
Axis=1, Adding new Columns

In [31]:
arr1=np.array([[2,4],[6,8]])
arr2=np.array([[3,5],[7,9]])
arr1=np.array([[3],[9]])
arr1=np.array([[4,8]])


In [33]:
new=np.concatenate((arr1,arr2),axis=0)
print(new)

[[4 8]
 [3 5]
 [7 9]]
